import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <header>1</header> */}
        <ConfigProvider
          theme={{
            token: {
              // Seed Token
              colorPrimary: '#388087',
              colorBorderBg: '#388087',
              colorIcon: '#388087',
              colorBgTextHover: '#6FB3B8',
              colorTextBase: '#388087',
              colorError: '#FF6961',


              // Alias Token
              colorBgContainer: '#FBF9F1',
            },
          }}
        >{children}</ConfigProvider>
        {/* <footer>2</footer> */}
      </body>
    </html>
  );
}
